### ISSUE TITLE
Prevent Keyboard from pushing up Tabbar

### ISSUE THREAD

**Issue by otymartin** [chicio/SwiftUI-CustomTabBar#1]
@chicio 

Hi - followed this tutorial today and it was a live saver. One small blemish i have yet to solve, in a currentView with a textfield, the keyboard pushes up the tabbar as of xcode 12, iOS 14 .

Any solutions to this? I will update if i find a solution unless then would appreciate some help 

Thanks

![image](https://user-images.githubusercontent.com/2222881/96066609-b28d7480-0e66-11eb-82a8-2dc1625e16f1.png)

**Comment by otymartin** [comment]
I fixed it by setting  `.ignoresSafeArea(.keyboard)` in my MainView's `VStack`
```swift
    var body: some View {
		VStack(spacing: 0) {
			CurrentScreen(currentView: $currentView)
			TabBar(currentView: $currentView, showCompose: $showModal)
		}
		.ignoresSafeArea(.keyboard)
  }
```

**Comment by chicio** [comment]
Thanks @otymartin for the feedback. I will add this to the source code example of the article (or if you want you can open a pull request in order to help and contribute 🙂).

**Comment by otymartin** [comment]
Thanks @chicio I will PR soon as I'm done my full implementation.

**Comment by chicio** [comment]
Hi @otymartin , no worries, I pushed the fix. Thank you again for your feedback.
